use crate::fs;
use crate::r#const::CILIUM_VERSION;
use crate::r#const::CNI_VERSION;
use crate::r#const::CONFIG_FILENAME;
use crate::r#const::CONTAINERD_VERSION;
use crate::r#const::K8S_VERSION;
use crate::r#const::RUNC_VERSION;
use crate::Path;
use anyhow::{Context, Result};

/// Write a `config.toml` scaffold to the current working directory.
pub fn generate() -> Result<()> {
    let path = Path::new(CONFIG_FILENAME);

    if path.exists() {
        anyhow::bail!("`{CONFIG_FILENAME}` already exists in the current directory");
    }

    let content = build_config(
        RUNC_VERSION,
        CNI_VERSION,
        CONTAINERD_VERSION,
        K8S_VERSION,
        CILIUM_VERSION,
    );

    fs::write(path, &content).with_context(|| format!("failed to write `{CONFIG_FILENAME}`"))?;

    println!(
        "✓ Created {CONFIG_FILENAME}  \
         (runc {RUNC_VERSION}, CNI plugins {CNI_VERSION}, \
         containerd {CONTAINERD_VERSION}, Kubernetes {K8S_VERSION}, \
         Cilium CLI {CILIUM_VERSION})"
    );
    Ok(())
}

/// Return the rendered TOML configuration string.
fn build_config(
    runc_version: &str,
    cni_version: &str,
    containerd_version: &str,
    k8s_version: &str,
    cilium_version: &str,
) -> String {
    format!(
        r#"# Generated by cisak

[runtime]
name    = "runc"
version = "{runc_version}"
binary  = "/usr/local/sbin/runc"

[cni]
version     = "{cni_version}"
install_dir = "/opt/cni/bin"

[containerd]
# Binaries are unpacked into <install_dir>/bin/ (e.g. /usr/local/bin/containerd)
version     = "{containerd_version}"
install_dir = "/usr/local"

[kubernetes]
# kubelet is installed to kubelet_install_dir; kubeadm + kubectl to install_dir.
version             = "{k8s_version}"
install_dir         = "/usr/local/bin"
kubelet_install_dir = "/usr/bin"

[cilium]
# Cilium CLI binary installed to <install_dir>/cilium.
version     = "{cilium_version}"
install_dir = "/usr/local/bin"

[network]
# Set net.ipv4.ip_forward = 1 (required for container networking).
# The setting is written to sysctl_conf_path for persistence across reboots.
ipv4_forward     = true
sysctl_conf_path = "/etc/sysctl.d/99-cisak.conf"
"#
    )
}
