[package]
name        = "cisak"
version     = "0.1.5"
edition     = "2021"
description = "Container Installation - Swiss Army Knife: automates download, verification, and installation of runc, CNI plugins, and containerd"
license     = "MIT"
repository  = "https://github.com/rodolfovillaruz/cisak"
readme      = "README.md"
keywords    = ["container", "runc", "containerd", "cni", "oci"]
categories  = ["command-line-utilities", "development-tools"]
exclude     = [".dump"]

[[bin]]
name = "cisak"
path = "src/main.rs"

[dependencies]
clap     = { version = "4",     features = ["derive"] }
serde    = { version = "1",     features = ["derive"] }
toml     = "1.1.2"
anyhow   = "1"
tempfile = "3"
