use anyhow::{Context, Result};
use clap::{Parser, Subcommand};
use serde::Deserialize;
use std::{fs, path::Path, path::PathBuf, process::Command as ProcCommand};

// ── CLI ──────────────────────────────────────────────────────────────────────

#[derive(Parser)]
#[command(
    name = "cisak",
    version,
    about = "Container Installation - Swiss Army Knife"
)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Install a container image
    Install {
        /// Image name  (e.g. ubuntu:22.04)
        image: String,

        /// Optional tag override
        #[arg(short, long)]
        tag: Option<String>,
    },

    /// Generate a config.toml file in the current directory
    Generate,

    /// Download, verify, and install the runc binary defined in config.toml
    Run,
}

// ── Constants ────────────────────────────────────────────────────────────────

const RUNC_VERSION: &str = "v1.4.2";
const CONFIG_FILENAME: &str = "config.toml";
const RUNC_INSTALL_PATH: &str = "/usr/local/sbin/runc";
const RUNC_URL_BASE: &str = "https://github.com/opencontainers/runc/releases/download";

// ── Config ───────────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize)]
struct Config {
    runtime: RuntimeConfig,
}

#[derive(Debug, Deserialize)]
struct RuntimeConfig {
    #[allow(dead_code)]
    name: String,
    version: String,
    binary: Option<String>,
}

fn load_config() -> Result<Config> {
    let raw = fs::read_to_string(CONFIG_FILENAME)
        .with_context(|| format!("failed to read `{CONFIG_FILENAME}`"))?;
    toml::from_str::<Config>(&raw).with_context(|| format!("failed to parse `{CONFIG_FILENAME}`"))
}

// ── Commands ─────────────────────────────────────────────────────────────────

/// Pull and register a container image on the host.
fn install(image: &str, tag: Option<&str>) -> Result<()> {
    let target = match tag {
        Some(t) => format!("{image}:{t}"),
        None => image.to_owned(),
    };

    println!("→ Installing: {target}");

    ProcCommand::new("docker")
        .args(["pull", &target])
        .status()
        .with_context(|| format!("failed to pull image `{target}`"))?;

    println!("✓ {target} installed.");
    Ok(())
}

/// Write a `config.toml` scaffold to the current working directory.
fn generate() -> Result<()> {
    let path = Path::new(CONFIG_FILENAME);

    if path.exists() {
        anyhow::bail!("`{CONFIG_FILENAME}` already exists in the current directory");
    }

    let content = build_config(RUNC_VERSION);

    fs::write(path, &content).with_context(|| format!("failed to write `{CONFIG_FILENAME}`"))?;

    println!("✓ Created {CONFIG_FILENAME}  (runc {RUNC_VERSION})");
    Ok(())
}

/// Return the rendered TOML configuration string.
fn build_config(runc_version: &str) -> String {
    format!(
        r#"# Generated by cisak

[runtime]
name    = "runc"
version = "{runc_version}"
binary  = "/usr/local/sbin/runc"

[container]
rootfs     = "./rootfs"
log_file   = "./container.log"
log_format = "json"

[namespaces]
pid     = true
network = true
ipc     = true
mount   = true
uts     = true

[resources]
memory_limit_mb = 512
cpu_shares      = 1024
"#
    )
}

/// Download runc + signature, verify, and install.
fn run() -> Result<()> {
    let cfg = load_config()?;
    let version = &cfg.runtime.version;
    let install_path = cfg
        .runtime
        .binary
        .clone()
        .unwrap_or_else(|| RUNC_INSTALL_PATH.to_string());

    println!("→ Using runc version: {version}");

    let bin_url = format!("{RUNC_URL_BASE}/{version}/runc.amd64");
    let sig_url = format!("{RUNC_URL_BASE}/{version}/runc.amd64.asc");

    let tmp = tempfile::tempdir().context("failed to create temporary directory")?;
    let bin_path = tmp.path().join("runc.amd64");
    let sig_path = tmp.path().join("runc.amd64.asc");

    download(&bin_url, &bin_path)?;
    download(&sig_url, &sig_path)?;

    verify_signature(&bin_path, &sig_path)?;

    install_binary(&bin_path, Path::new(&install_path))?;

    println!("✓ runc {version} installed to {install_path}");
    Ok(())
}

// ── Helpers ──────────────────────────────────────────────────────────────────

/// Download a URL to a local path using `curl`.
fn download(url: &str, dest: &Path) -> Result<()> {
    println!("→ Downloading {url}");

    let status = ProcCommand::new("curl")
        .args([
            "--fail",
            "--silent",
            "--show-error",
            "--location",
            "--output",
        ])
        .arg(dest)
        .arg(url)
        .status()
        .with_context(|| format!("failed to execute `curl` for {url}"))?;

    if !status.success() {
        anyhow::bail!("curl failed to download {url} (exit {status})");
    }

    Ok(())
}

/// Verify a detached GPG signature.
fn verify_signature(bin: &Path, sig: &Path) -> Result<()> {
    println!("→ Verifying signature…");

    let output = ProcCommand::new("gpg")
        .arg("--verify")
        .arg(sig)
        .arg(bin)
        .output()
        .context("failed to execute `gpg` (is it installed?)")?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        anyhow::bail!(
            "signature verification FAILED for `{}` against `{}`:\n{}",
            bin.display(),
            sig.display(),
            stderr.trim()
        );
    }

    println!("✓ Signature verified");
    Ok(())
}

/// Copy the verified binary into place and make it executable.
fn install_binary(src: &Path, dest: &Path) -> Result<()> {
    if let Some(parent) = dest.parent() {
        if !parent.exists() {
            fs::create_dir_all(parent)
                .with_context(|| format!("failed to create `{}`", parent.display()))?;
        }
    }

    // Try a straight copy first; fall back to `sudo install` if that fails
    // (e.g. because the destination lives in /usr/local/sbin).
    if fs::copy(src, dest).is_err() {
        let status = ProcCommand::new("sudo")
            .args(["install", "-m", "0755"])
            .arg(src)
            .arg(dest)
            .status()
            .with_context(|| format!("failed to install binary to `{}`", dest.display()))?;
        if !status.success() {
            anyhow::bail!("sudo install failed (exit {status})");
        }
    } else {
        chmod_executable(dest)?;
    }

    Ok(())
}

#[cfg(unix)]
fn chmod_executable(path: &Path) -> Result<()> {
    use std::os::unix::fs::PermissionsExt;
    let mut perms = fs::metadata(path)?.permissions();
    perms.set_mode(0o755);
    fs::set_permissions(path, perms)
        .with_context(|| format!("failed to chmod `{}`", path.display()))?;
    Ok(())
}

#[cfg(not(unix))]
fn chmod_executable(_path: &Path) -> Result<()> {
    Ok(())
}

// Silence warnings for unused `PathBuf` re-exports on some targets.
#[allow(dead_code)]
fn _unused(_: PathBuf) {}

// ── Entry point ──────────────────────────────────────────────────────────────

fn main() -> Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Command::Install { image, tag } => install(&image, tag.as_deref())?,
        Command::Generate => generate()?,
        Command::Run => run()?,
    }

    Ok(())
}
