use anyhow::{Context, Result};
use clap::{Parser, Subcommand};
use std::{fs, path::Path};

// ── CLI ──────────────────────────────────────────────────────────────────────

#[derive(Parser)]
#[command(
    name = "cisak",
    version,
    about = "Container Installation - Swiss Army Knife"
)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Install a container image
    Install {
        /// Image name  (e.g. ubuntu:22.04)
        image: String,

        /// Optional tag override
        #[arg(short, long)]
        tag: Option<String>,
    },

    /// Generate a config.hcl file in the current directory
    Generate,
}

// ── Constants ────────────────────────────────────────────────────────────────

const RUNC_VERSION: &str = "v1.4.2";
const CONFIG_FILENAME: &str = "config.hcl";

// ── Functions ────────────────────────────────────────────────────────────────

/// Pull and register a container image on the host.
fn install(image: &str, tag: Option<&str>) -> Result<()> {
    let target = match tag {
        Some(t) => format!("{image}:{t}"),
        None => image.to_owned(),
    };

    println!("→ Installing: {target}");

    // TODO: shell out to `docker pull` / `podman pull` / containerd gRPC
    std::process::Command::new("docker")
        .args(["pull", &target])
        .status()
        .with_context(|| format!("failed to pull image `{target}`"))?;

    println!("✓ {target} installed.");
    Ok(())
}

/// Write a `config.hcl` scaffold to the current working directory.
fn generate() -> Result<()> {
    let path = Path::new(CONFIG_FILENAME);

    if path.exists() {
        anyhow::bail!("`{CONFIG_FILENAME}` already exists in the current directory");
    }

    let content = build_config(RUNC_VERSION);

    fs::write(path, &content).with_context(|| format!("failed to write `{CONFIG_FILENAME}`"))?;

    println!("✓ Created {CONFIG_FILENAME}  (runc {RUNC_VERSION})");
    Ok(())
}

/// Return the rendered HCL configuration string.
fn build_config(runc_version: &str) -> String {
    format!(
        r#"# Generated by cisak

runtime {{
  name    = "runc"
  version = "{runc_version}"
  binary  = "/usr/local/sbin/runc"
}}

container {{
  rootfs     = "./rootfs"
  log_file   = "./container.log"
  log_format = "json"
}}

namespaces {{
  pid     = true
  network = true
  ipc     = true
  mount   = true
  uts     = true
}}

resources {{
  memory_limit_mb = 512
  cpu_shares      = 1024
}}
"#
    )
}

// ── Entry point ──────────────────────────────────────────────────────────────

fn main() -> Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Command::Install { image, tag } => {
            install(&image, tag.as_deref())?;
        }
        Command::Generate => {
            generate()?;
        }
    }

    Ok(())
}
